
/*
 *
 */

package myservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Aug 12 14:11:47 CEST 2015
 * Generated source version: 2.2.3
 *
 */


@WebServiceClient(name = "MyService",
                  wsdlLocation = "file:/home/blackshark/tmp/spring-soap/src/main/resources/wsdl/MyService.wsdl",
                  targetNamespace = "http://www.madbit.org/MyService/")
public class MyService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.madbit.org/MyService/", "MyService");
    public final static QName MyServiceSOAP = new QName("http://www.madbit.org/MyService/", "MyServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/blackshark/tmp/spring-soap/src/main/resources/wsdl/MyService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/blackshark/tmp/spring-soap/src/main/resources/wsdl/MyService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MyService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceSOAP")
    public MyService getMyServiceSOAP() {
        return super.getPort(MyServiceSOAP, MyService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceSOAP")
    public MyService getMyServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MyServiceSOAP, MyService.class, features);
    }

}
