package myservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Aug 12 14:11:47 CEST 2015
 * Generated source version: 2.2.3
 *
 */

@WebService(targetNamespace = "http://www.madbit.org/MyService/", name = "MyService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyService {

    @WebMethod(operationName = "Sum", action = "http://www.madbit.org/MyService/Sum")
    @WebResult(name = "SumResponse", targetNamespace = "http://www.madbit.org/MyService/", partName = "parameters")
    public SumResponse sum(
        @WebParam(partName = "parameters", name = "SumRequest", targetNamespace = "http://www.madbit.org/MyService/")
        SumRequest parameters
    );
}
